KingBudget/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingBudget.Models;

namespace KingBudget.Controllers
{
    public class BankAccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BankAccounts
        [Authorize]
        public ActionResult Index()
        {
            var bankAccounts = db.BankAccounts.Include(b => b.Household);
            return View(bankAccounts.ToList());
        }

        [Authorize]
        // GET: BankAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            return View(bankAccount);
        }

        [Authorize]
        // GET: BankAccounts/Create
        public ActionResult Create(int id)
        {
            ViewBag.HouseHoldId = id;
            return View();
        }

        // POST: BankAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Balance")] BankAccount bankAccount, int hId)
        {
            if (ModelState.IsValid)
            {
       
                bankAccount.HouseHoldId = hId;
                db.BankAccounts.Add(bankAccount);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            ViewBag.HouseHoldId = hId;
            return View(bankAccount);
        }

        [Authorize]
        // GET: BankAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            ViewBag.HouseHoldId = bankAccount.HouseHoldId;
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,HouseHoldId,Name,Balance")] BankAccount bankAccount, int baId)
        {
            if (ModelState.IsValid)
            {
                
                bankAccount.HouseHoldId = baId;
                db.Entry(bankAccount).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HouseHoldId = new SelectList(db.HouseHolds, "Id", "Name", bankAccount.HouseHoldId);
            return View(bankAccount);
        }

        [Authorize]
        // GET: BankAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BankAccount bankAccount = db.BankAccounts.Find(id);
            if (bankAccount == null)
            {
                return HttpNotFound();
            }
            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BankAccount bankAccount = db.BankAccounts.Find(id);
            db.BankAccounts.Remove(bankAccount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KingBudget/Controllers/HomeController.cs
using KingBudget.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KingBudget.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize]
        public ActionResult Index()
        {
            return View(db.HouseHolds.ToList());
        }
        [Authorize]

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        [Authorize]

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

KingBudget/Controllers/HouseHoldsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingBudget.Models;
using Microsoft.AspNet.Identity;
using KingBudget.Models.Helper;

namespace KingBudget.Controllers
{
    public class HouseHoldsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: HouseHolds
        [Authorize]
        public ActionResult Index()
        {
            return View(db.HouseHolds.ToList());
        }
        [Authorize]

        // GET: Leavehousehold
        [HttpGet]
        public ActionResult LeaveHousehold(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold household = db.HouseHolds.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LeaveHousehold(int id)
        {
            HouseHoldInvite helper = new HouseHoldInvite(db);
            string userId = User.Identity.GetUserId();

            helper.RemoveHouseholdFromUser(id, userId);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        // GET: HouseHolds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }

        [Authorize]
        // GET: HouseHolds/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HouseHolds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Created")] HouseHold houseHold)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                houseHold.CreatorId = userId;
                houseHold.Users.Add(db.Users.Find(User.Identity.GetUserId()));
                db.HouseHolds.Add(houseHold);
                houseHold.Created = new DateTimeOffset(DateTime.Now);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(houseHold);
        }

        [Authorize]
        // GET: HouseHolds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }

        // POST: HouseHolds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Balance,IsDeleted,Created,Updated")] HouseHold houseHold)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                houseHold.CreatorId = userId;
                db.Entry(houseHold).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(houseHold);
        }

        [Authorize]
        // GET: HouseHolds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }

        // POST: HouseHolds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HouseHold houseHold = db.HouseHolds.Find(id);
            db.HouseHolds.Remove(houseHold);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KingBudget/Controllers/InvitesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingBudget.Models;
using KingBudget.Models.Helper;
using System.Net.Mail;
using System.Configuration;
using System.Threading.Tasks;

namespace KingBudget.Controllers
{
    public class InvitesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        // GET: Invites
        public ActionResult Index()
        {
            return View(db.Invites.ToList());
        }

        [Authorize]
        // GET: Invites/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invite invite = db.Invites.Find(id);
            if (invite == null)
            {
                return HttpNotFound();
            }
            return View(invite);
        }

        [Authorize]
        // GET: Invites/Create
        public ActionResult Create(int id)
        {
            ViewBag.HouseHoldId = id;
            return View();
        }

        // POST: Invites/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Email,Secret")] Invite invite, int hId)
         {
            if (ModelState.IsValid)
            {

                invite.HouseHoldId = hId;
                invite.Secret = Utilities.GenerateSecretCode();
                var email = new MailMessage(ConfigurationManager.AppSettings["username"], invite.Email)
                {
                    Subject = "Join Household",
                    Body = "You have been invited to join a household in the budget tool. Select -Join- on log in, and input the code: " + invite.Secret + ".\n" +
                    "Or, <a href=\"" + Url.Action("InviteRegister", "Account", new { secret = invite.Secret, HouseholdId = invite.HouseHoldId }, protocol: Request.Url.Scheme) + "\">Click here</a> to join."
                };
                db.Invites.Add(invite);
                db.SaveChanges();
                var svc = new PersonalEmail();
                await svc.SendAsync(email);
                return RedirectToAction("Index","Home");
            }

            return View(invite);

        }

        [Authorize]
        // GET: Invites/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invite invite = db.Invites.Find(id);
            if (invite == null)
            {
                return HttpNotFound();
            }
            return View(invite);
        }

        // POST: Invites/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,HouseHoldId,Secret")] Invite invite)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invite).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(invite);
        }

        [Authorize]
        // GET: Invites/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invite invite = db.Invites.Find(id);
            if (invite == null)
            {
                return HttpNotFound();
            }
            return View(invite);
        }

        [Authorize]
        // POST: Invites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invite invite = db.Invites.Find(id);
            db.Invites.Remove(invite);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KingBudget/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

KingBudget/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

KingBudget/Views/Home/T_Index.cshtml
@model IEnumerable<KingBudget.Models.HouseHold>
@{
    ViewBag.Title = "Budgeter";
    double budgetAmount = 0.00;
}
@* Adding Template *@

@* HouseHold *@
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="text-center">House Hold</h1>
            <a href="@Url.Action("Create", "HouseHolds")" class="text-center">Create House</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>HouseHold Members <text>&nbsp;</text></th>
                        <th>Functions</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>
                                @foreach (var name in item.Users)
                                {
                                    if (name.DisplayName != null)
                                    {
                                        @name.DisplayName
                                    }
                                    else
                                    {
                                        @name.Email
                                    }
                                    <br>
                                }
                            </td>
                            <td>
                                @Html.ActionLink("Budget Item", "Create", "Items", new { id = item.Id }, "") <br>
                                @Html.ActionLink("BankAccount", "Create", "BankAccounts", new { id = item.Id }, "") <br>
                                @Html.ActionLink("Invite", "Create", "Invites", new { id = item.Id }, "") <br>
                                @Html.ActionLink("Edit", "Edit", "HouseHolds", new { id = item.Id }, "") <br>
                                @Html.ActionLink("Details", "Details", "HouseHolds", new { id = item.Id }, "") <br>
                                @Html.ActionLink("Delete", "Delete", "HouseHolds", new { id = item.Id }, "")
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>
<br>
<br>
<br>
<br>
@* Accounts *@
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="text-center">Accounts</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>HouseHold Name</th>
                        <th>Account Name</th>
                        <th>Balance</th>
                        <th>Functions</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {

                        foreach (var account in item.BankAccounts)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@account.Name</td>
                                @if (account.Balance > 0)
                                {
                                    <td style="color:green">@account.Balance.ToString("C")</td>
                                }
                                else if (account.Balance < 0)
                                {
                                    <td style="color:red">@account.Balance.ToString("C")</td>
                                }
                                <td>
                                    @Html.ActionLink("Transaction", "Create", "Transactions", new { id = account.Id }, "") <br>
                                    @Html.ActionLink("Edit", "Edit", "BankAccounts", new { id = item.Id }, "") <br>
                                    @Html.ActionLink("Details", "Details", "BankAccounts", new { id = item.Id }, "") <br>
                                    @Html.ActionLink("Delete", "Delete", "BankAccounts", new { id = item.Id }, "")
                                </td>
                            </tr>
                        }

                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
@* Transactions *@
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="text-center">Transactions Expense</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>Posted Date</th>
                        @*<th>Transaction Date</th>*@
                        <th>HouseHold Account</th>
                        <th>Description</th>
                        <th>Category</th>
                        <th>Debit</th>
                        <th>Credit</th>
                        <th>Functions</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        foreach (var account in item.BankAccounts)
                        {
                            foreach (var transaction in account.Transactions.Where(t => t.Type.Name == "Expense"))
                            {
                                <tr>
                                    <td>@transaction.Created.ToString("MM/dd/yyyy")</td>
                                    @*<td>@transaction.Date.ToString("MM/dd/yyyy")</td>*@
                                    <td>@transaction.BankAccount.Name</td>
                                    <td>@Html.Raw(transaction.Description)</td>
                                    <td>@Html.Raw(transaction.Category.Name)</td>
                                    @if (transaction.TypeId != 21)
                                    {
                                        <td style="color:red">(-) @Html.Raw(transaction.Amount.ToString("C"))</td>
                                        <td></td>
                                    }
                                    else
                                    {
                                        <td></td>
                                        <td style="color:green">(+) @Html.Raw(transaction.Amount.ToString("C"))</td>
                                    }
                                    <td>
                                        @*@Html.ActionLink("BankAccount", "Create", "BankAccounts", new { id = item.Id }, "") <br>
                                            @Html.ActionLink("Invite", "Create", "Invites", new { id = item.Id }, "") <br>*@
                                        @Html.ActionLink("Edit", "Edit", "Transactions", new { id = transaction.Id }, "") <br>
                                        @Html.ActionLink("Details", "Details", "Transactions", new { id = transaction.Id }, "") <br>
                                        @Html.ActionLink("Delete", "Delete", "Transactions", new { id = transaction.Id }, "")
                                    </td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
            <h1 class="text-center">Transactions Income</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>Posted Date</th>
                        @*<th>Transaction Date</th>*@
                        <th>HouseHold Account</th>
                        <th>Description</th>
                        <th>Category</th>
                        <th>Debit</th>
                        <th>Credit</th>
                        <th>Functions</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        foreach (var account in item.BankAccounts)
                        {
                            foreach (var transaction in account.Transactions.Where(t => t.Type.Name == "Income"))
                            {
                                <tr>
                                    <td>@transaction.Created.ToString("MM/dd/yyyy")</td>
                                    @*<td>@transaction.Date.ToString("MM/dd/yyyy")</td>*@
                                    <td>@transaction.BankAccount.Name</td>
                                    <td>@Html.Raw(transaction.Description)</td>
                                    <td>@Html.Raw(transaction.Category.Name)</td>
                                    @if (transaction.TypeId != 1)
                                    {
                                        <td style="color:red">(-) @Html.Raw(transaction.Amount.ToString("C"))</td>
                                        <td></td>
                                    }
                                    else
                                    {
                                        <td></td>
                                        <td style="color:green">(+) @Html.Raw(transaction.Amount.ToString("C"))</td>
                                    }
                                    <td>
                                        @*@Html.ActionLink("BankAccount", "Create", "BankAccounts", new { id = item.Id }, "") <br>
                                            @Html.ActionLink("Invite", "Create", "Invites", new { id = item.Id }, "") <br>*@
                                        @Html.ActionLink("Edit", "Edit", "Transactions", new { id = transaction.Id }, "") <br>
                                        @Html.ActionLink("Details", "Details", "Transactions", new { id = transaction.Id }, "") <br>
                                        @Html.ActionLink("Delete", "Delete", "Transactions", new { id = transaction.Id }, "")
                                    </td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>
<br>
<br>
<br>
<br>
@* Budget *@
<h1 class="text-center">Budget</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            @foreach (var item in Model)
            {
                foreach (var key in item.Items)
                {
                    budgetAmount += key.Amount;
                }
            }
            <h1 class="text-center" style="color:Green">@budgetAmount.ToString("C")</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Amount</th>
                        <th>Functions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        foreach (var key in item.Items)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@key.Category.Name</td>
                                <td>@key.Amount.ToString("C")</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", "Items", new { id = key.Id }, "") <br />
                                    @Html.ActionLink("Details", "Details", "Items", new { id = key.Id }, "") <br />
                                    @Html.ActionLink("Delete", "Delete", "Items", new { id = key.Id }, "")
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>